In [23]:
import numpy as np

In [32]:
x = "GATTACA"
y = "GAACA"

lenx = len(x)
leny = len(y)

In [33]:
F = np.zeros((lenx+1, leny+1))
F[:,0] = np.linspace(0, -lenx * 1, lenx + 1)
F[0,:] = np.linspace(0, -leny * 1, leny + 1)
F

array([[ 0., -1., -2., -3., -4., -5.],
       [-1.,  0.,  0.,  0.,  0.,  0.],
       [-2.,  0.,  0.,  0.,  0.,  0.],
       [-3.,  0.,  0.,  0.,  0.,  0.],
       [-4.,  0.,  0.,  0.,  0.,  0.],
       [-5.,  0.,  0.,  0.,  0.,  0.],
       [-6.,  0.,  0.,  0.,  0.,  0.],
       [-7.,  0.,  0.,  0.,  0.,  0.]])

In [34]:
P = np.zeros((lenx+1, leny+1))
P[:,0]=3
P[0,:]=4
P

array([[4., 4., 4., 4., 4., 4.],
       [3., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0.]])

In [35]:
t = np.zeros(3)
t

array([0., 0., 0.])

In [ ]:
def mismatch_score(x, y):
    if((x=='A') and (y=='G')) or ((x=='G') and (y=='A')):
        mismatch = 1
    elif((x=='C') and (y=='T')) or ((x=='T') and (y=='C')):
        mismatch = 1
    elif((x=='A') and (y=='T')) or ((x=='T') and (y=='A')):
        mismatch = 4
    elif((x=='C') and (y=='G')) or ((x=='G') and (y=='C')):
        mismatch = 4
    elif(x=='' and y==""):
        mismatch = 1
    else:
        mismatch = 2
    return mismatch

In [36]:
match = 5
mismatch = 1
gap =1
for i in range(lenx):
    for j in range(leny):
        if x[i] == y[j]:
            t[0] = F[i,j] + match
        else:
            t[0] = F[i,j] - mismatch_score(x[i], x[j])
        t[1] = F[i,j+1] - gap
        t[2] = F[i+1,j] - gap
        tmax = np.max(t)
        F[i+1,j+1] = tmax
        if t[0] == tmax:
            P[i+1,j+1] += 2
        if t[1] == tmax:
            P[i+1,j+1] += 3
        if t[2] == tmax:
            P[i+1,j+1] += 4

In [37]:
P

array([[4., 4., 4., 4., 4., 4.],
       [3., 2., 4., 4., 4., 4.],
       [3., 3., 2., 6., 4., 6.],
       [3., 3., 3., 2., 6., 6.],
       [3., 3., 3., 5., 2., 6.],
       [3., 3., 5., 2., 4., 2.],
       [3., 3., 3., 3., 2., 4.],
       [3., 3., 5., 5., 3., 2.]])

In [38]:
i = lenx
j = leny
rx=[]
ry=[]
while i > 0 or j > 0:
    if P[i,j] in [2, 5, 6, 9]:
        rx.append(x[i-1])
        ry.append(y[j-1])
        i -= 1
        j -= 1
    elif P[i,j] in [3, 5, 7, 9]:
        rx.append(x[i-1])
        ry.append('-')
        i -= 1
    elif P[i,j] in [4, 6, 7, 9]:
        rx.append('-')
        ry.append(y[j-1])
        j -= 1

In [39]:
rx

['A', 'C', 'A', 'T', 'T', 'A', 'G']